// flow-typed signature: 8bfe25cbf9ae131da33053a5dca862d9
// flow-typed version: <<STUB>>/mobx-utils_v^2.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-utils/lib/chunk-processor' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/create-view-model' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/from-promise' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/from-resource' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/guarded-when' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/keep-alive' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/lazy-observable' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/mobx-utils' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/now' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/observable-stream' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/queue-processor' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/subscribing-observable' {
  declare module.exports: any;
}

declare module 'mobx-utils/lib/utils' {
  declare module.exports: any;
}

declare module 'mobx-utils/mobx-utils.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-utils/lib/chunk-processor.js' {
  declare module.exports: $Exports<'mobx-utils/lib/chunk-processor'>;
}
declare module 'mobx-utils/lib/create-view-model.js' {
  declare module.exports: $Exports<'mobx-utils/lib/create-view-model'>;
}
declare module 'mobx-utils/lib/from-promise.js' {
  declare module.exports: $Exports<'mobx-utils/lib/from-promise'>;
}
declare module 'mobx-utils/lib/from-resource.js' {
  declare module.exports: $Exports<'mobx-utils/lib/from-resource'>;
}
declare module 'mobx-utils/lib/guarded-when.js' {
  declare module.exports: $Exports<'mobx-utils/lib/guarded-when'>;
}
declare module 'mobx-utils/lib/keep-alive.js' {
  declare module.exports: $Exports<'mobx-utils/lib/keep-alive'>;
}
declare module 'mobx-utils/lib/lazy-observable.js' {
  declare module.exports: $Exports<'mobx-utils/lib/lazy-observable'>;
}
declare module 'mobx-utils/lib/mobx-utils.js' {
  declare module.exports: $Exports<'mobx-utils/lib/mobx-utils'>;
}
declare module 'mobx-utils/lib/now.js' {
  declare module.exports: $Exports<'mobx-utils/lib/now'>;
}
declare module 'mobx-utils/lib/observable-stream.js' {
  declare module.exports: $Exports<'mobx-utils/lib/observable-stream'>;
}
declare module 'mobx-utils/lib/queue-processor.js' {
  declare module.exports: $Exports<'mobx-utils/lib/queue-processor'>;
}
declare module 'mobx-utils/lib/subscribing-observable.js' {
  declare module.exports: $Exports<'mobx-utils/lib/subscribing-observable'>;
}
declare module 'mobx-utils/lib/utils.js' {
  declare module.exports: $Exports<'mobx-utils/lib/utils'>;
}
declare module 'mobx-utils/mobx-utils.umd.js' {
  declare module.exports: $Exports<'mobx-utils/mobx-utils.umd'>;
}
