// flow-typed signature: 43e8243b12e7234692a30b6effa0b997
// flow-typed version: <<STUB>>/mobx-persist_v^0.3.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-persist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-persist/lib/index' {
  declare module.exports: any;
}

declare module 'mobx-persist/lib/merge-x' {
  declare module.exports: any;
}

declare module 'mobx-persist/lib/persist-object' {
  declare module.exports: any;
}

declare module 'mobx-persist/lib/storage' {
  declare module.exports: any;
}

declare module 'mobx-persist/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-persist/lib/index.js' {
  declare module.exports: $Exports<'mobx-persist/lib/index'>;
}
declare module 'mobx-persist/lib/merge-x.js' {
  declare module.exports: $Exports<'mobx-persist/lib/merge-x'>;
}
declare module 'mobx-persist/lib/persist-object.js' {
  declare module.exports: $Exports<'mobx-persist/lib/persist-object'>;
}
declare module 'mobx-persist/lib/storage.js' {
  declare module.exports: $Exports<'mobx-persist/lib/storage'>;
}
declare module 'mobx-persist/lib/types.js' {
  declare module.exports: $Exports<'mobx-persist/lib/types'>;
}
