// flow-typed signature: 62ff2ec69ce890926feff145b4ec0d36
// flow-typed version: <<STUB>>/react-native-navbar_v^1.6.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-navbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-navbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-navbar/NavbarButton' {
  declare module.exports: any;
}

declare module 'react-native-navbar/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-navbar/index' {
  declare module.exports: $Exports<'react-native-navbar'>;
}
declare module 'react-native-navbar/index.js' {
  declare module.exports: $Exports<'react-native-navbar'>;
}
declare module 'react-native-navbar/NavbarButton.js' {
  declare module.exports: $Exports<'react-native-navbar/NavbarButton'>;
}
declare module 'react-native-navbar/styles.js' {
  declare module.exports: $Exports<'react-native-navbar/styles'>;
}
