// flow-typed signature: 425f8560ce9d1132caa8ce89e1299446
// flow-typed version: <<STUB>>/react-native-version_v^2.3.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-version/cli' {
  declare module.exports: any;
}

declare module 'react-native-version/test/cli.amend' {
  declare module.exports: any;
}

declare module 'react-native-version/test/cli.amend.skipTag' {
  declare module.exports: any;
}

declare module 'react-native-version/test/cli.default' {
  declare module.exports: any;
}

declare module 'react-native-version/test/cli.neverAmend' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/beforeEach' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/beforeEachCLI' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/execAsync' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/getCurrCommitHash' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/getCurrTagHash' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/getCurrTree' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/gitPathnames' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/injectPackageJSON' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/tempInitAndVersion' {
  declare module.exports: any;
}

declare module 'react-native-version/test/helpers/versionTempWithCLI' {
  declare module.exports: any;
}

declare module 'react-native-version/test/index' {
  declare module.exports: any;
}

declare module 'react-native-version/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-version/cli.js' {
  declare module.exports: $Exports<'react-native-version/cli'>;
}
declare module 'react-native-version/index' {
  declare module.exports: $Exports<'react-native-version'>;
}
declare module 'react-native-version/index.js' {
  declare module.exports: $Exports<'react-native-version'>;
}
declare module 'react-native-version/test/cli.amend.js' {
  declare module.exports: $Exports<'react-native-version/test/cli.amend'>;
}
declare module 'react-native-version/test/cli.amend.skipTag.js' {
  declare module.exports: $Exports<'react-native-version/test/cli.amend.skipTag'>;
}
declare module 'react-native-version/test/cli.default.js' {
  declare module.exports: $Exports<'react-native-version/test/cli.default'>;
}
declare module 'react-native-version/test/cli.neverAmend.js' {
  declare module.exports: $Exports<'react-native-version/test/cli.neverAmend'>;
}
declare module 'react-native-version/test/helpers/beforeEach.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/beforeEach'>;
}
declare module 'react-native-version/test/helpers/beforeEachCLI.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/beforeEachCLI'>;
}
declare module 'react-native-version/test/helpers/execAsync.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/execAsync'>;
}
declare module 'react-native-version/test/helpers/getCurrCommitHash.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/getCurrCommitHash'>;
}
declare module 'react-native-version/test/helpers/getCurrTagHash.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/getCurrTagHash'>;
}
declare module 'react-native-version/test/helpers/getCurrTree.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/getCurrTree'>;
}
declare module 'react-native-version/test/helpers/gitPathnames.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/gitPathnames'>;
}
declare module 'react-native-version/test/helpers/injectPackageJSON.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/injectPackageJSON'>;
}
declare module 'react-native-version/test/helpers/tempInitAndVersion.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/tempInitAndVersion'>;
}
declare module 'react-native-version/test/helpers/versionTempWithCLI.js' {
  declare module.exports: $Exports<'react-native-version/test/helpers/versionTempWithCLI'>;
}
declare module 'react-native-version/test/index.js' {
  declare module.exports: $Exports<'react-native-version/test/index'>;
}
declare module 'react-native-version/util.js' {
  declare module.exports: $Exports<'react-native-version/util'>;
}
