// flow-typed signature: a1c5892089af14715177497ac815c8a4
// flow-typed version: <<STUB>>/react-native-keyboard-aware-scrollview_v^1.1.5/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keyboard-aware-scrollview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keyboard-aware-scrollview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-keyboard-aware-scrollview/src/KeyboardAwareBase' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-aware-scrollview/src/KeyboardAwareListView' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-aware-scrollview/src/KeyboardAwareScrollView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-keyboard-aware-scrollview/index' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scrollview'>;
}
declare module 'react-native-keyboard-aware-scrollview/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scrollview'>;
}
declare module 'react-native-keyboard-aware-scrollview/src/KeyboardAwareBase.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scrollview/src/KeyboardAwareBase'>;
}
declare module 'react-native-keyboard-aware-scrollview/src/KeyboardAwareListView.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scrollview/src/KeyboardAwareListView'>;
}
declare module 'react-native-keyboard-aware-scrollview/src/KeyboardAwareScrollView.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scrollview/src/KeyboardAwareScrollView'>;
}
