// flow-typed signature: 6c5584f534500bf8591eb1190babf877
// flow-typed version: <<STUB>>/react-native-responsive-dimensions_v^1.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-responsive-dimensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-responsive-dimensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-responsive-dimensions/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-responsive-dimensions/src/index.js' {
  declare module.exports: $Exports<'react-native-responsive-dimensions/src/index'>;
}
