// flow-typed signature: 6f8d48181989c3809cb52698ba8f251d
// flow-typed version: <<STUB>>/react-native-charts-wrapper_v^0.2.7/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-charts-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-charts-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-charts-wrapper/Example/app/AxisLineChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/BarChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/BubbleChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/CandleStickChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/ChartsListScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/CombinedChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/GroupBarChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/HorizontalBarChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/LineChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/LiveUpdateChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/PieChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/RadarChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/ScatterChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/StackedBarChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/TimeSeriesLineChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/app/ZeroLineChartScreen' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/Example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/AxisIface' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/BarChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/BarLineChartBase' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/BubbleChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/CandleStickChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ChartBase' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ChartDataConfig' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ChartDataSetConfig' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/CombinedChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/HorizontalBarChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/LineChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/PieChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/PieRadarChartBase' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/RadarChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ScatterChart' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-charts-wrapper/Example/app/AxisLineChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/AxisLineChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/BarChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/BarChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/BubbleChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/BubbleChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/CandleStickChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/CandleStickChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/ChartsListScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/ChartsListScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/CombinedChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/CombinedChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/GroupBarChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/GroupBarChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/HorizontalBarChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/HorizontalBarChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/LineChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/LineChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/LiveUpdateChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/LiveUpdateChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/PieChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/PieChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/RadarChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/RadarChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/ScatterChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/ScatterChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/StackedBarChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/StackedBarChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/TimeSeriesLineChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/TimeSeriesLineChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/app/ZeroLineChartScreen.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/app/ZeroLineChartScreen'>;
}
declare module 'react-native-charts-wrapper/Example/index.android.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/index.android'>;
}
declare module 'react-native-charts-wrapper/Example/index.ios.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/Example/index.ios'>;
}
declare module 'react-native-charts-wrapper/index' {
  declare module.exports: $Exports<'react-native-charts-wrapper'>;
}
declare module 'react-native-charts-wrapper/index.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper'>;
}
declare module 'react-native-charts-wrapper/lib/AxisIface.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/AxisIface'>;
}
declare module 'react-native-charts-wrapper/lib/BarChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/BarChart'>;
}
declare module 'react-native-charts-wrapper/lib/BarLineChartBase.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/BarLineChartBase'>;
}
declare module 'react-native-charts-wrapper/lib/BubbleChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/BubbleChart'>;
}
declare module 'react-native-charts-wrapper/lib/CandleStickChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/CandleStickChart'>;
}
declare module 'react-native-charts-wrapper/lib/ChartBase.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ChartBase'>;
}
declare module 'react-native-charts-wrapper/lib/ChartDataConfig.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ChartDataConfig'>;
}
declare module 'react-native-charts-wrapper/lib/ChartDataSetConfig.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ChartDataSetConfig'>;
}
declare module 'react-native-charts-wrapper/lib/CombinedChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/CombinedChart'>;
}
declare module 'react-native-charts-wrapper/lib/HorizontalBarChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/HorizontalBarChart'>;
}
declare module 'react-native-charts-wrapper/lib/LineChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/LineChart'>;
}
declare module 'react-native-charts-wrapper/lib/PieChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/PieChart'>;
}
declare module 'react-native-charts-wrapper/lib/PieRadarChartBase.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/PieRadarChartBase'>;
}
declare module 'react-native-charts-wrapper/lib/RadarChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/RadarChart'>;
}
declare module 'react-native-charts-wrapper/lib/ScatterChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ScatterChart'>;
}
