platform :ios, '9.0'
use_frameworks!

def shared_pods
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftyJSON', '3.1.4'
    pod 'Charts', '3.0.1'
end

def debug_pods

end

target 'SantimentMobile' do
    shared_pods
    debug_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
